spring:
  application:
    name: oauth2-server

com:
  thelastimperial:
    oauth2_server:
      keypair:
        public: PubliStringKey
        private: PrivateStringKey
      webauthn:
        rpid: localhost
        allowedorigins: http://localhost,http://localhost2,http://localhost3
